### ISSUE TITLE
Tiles not loading

### ISSUE THREAD

**Issue by Tvax** [Multiware-Tecnologia/react-native-open-street-map#10]
**Describe the bug**
The tiles don't load from Open Street Map

**To Reproduce**
1. Copy this in package.json:
 `"react-native-open-street-map": "https://github.com/enieber/react-native-open-street-map.git"`
2. Copy all android code into files
3. Launch the app with internet activated

**Expected behavior**
Tiles should be displayed

**Screenshots**
![screenshot from 2019-01-19 22-43-58](https://user-images.githubusercontent.com/19556689/51432683-f0cb1500-1c3b-11e9-9d99-c8fdf9751a76.png)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android 7.1

**Additional context**
Thank you for making this module nonetheless !

**Comment by koka0012** [comment]
@Tvax fixed?

**Comment by Tvax** [comment]
I've not been able to test it yet.
I'll do it in the following days, and send you a feedback!

**Comment by Tvax** [comment]
Enabling storage permission has fixed the problem, thank you !
Should we add it to the README?

**Comment by koka0012** [comment]
> Enabling storage permission has fixed the problem, thank you !
> Should we add it to the README?

Yes, ofc, just open a PR.
